version: '3'
services:
  py3:
    build: .
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/app
    expose:
      - "8888"
      - "8000"
    ports:
      - "127.0.0.1:8888:8888"
      - "127.0.0.1:8000:8000"
    volumes:
      - ./app:/app
