version: '3'
services:
  webserver:
    build: .
    image: node-express-dev:1.0
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "8080:3000"

  py3:
    build: .
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/app
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./app:/app
